language: java
dist: trusty

jdk:
  - openjdk-ea
  - openjdk12
  - oraclejdk11
  - oraclejdk8

after_success:
  - if [[ $TRAVIS_JDK_VERSION == "oraclejdk8" ]]; then ./mvnw jacoco:report coveralls:report; fi
